host: "YOUR HOSTNAME"
queryPort: "QUERYPORT (default: 10011)"
queryName: "QUERY NAME"
queryPassword: "QUERY PASSWORD"
virtualServerId: "VIRTUAL SERVER ID"
botUserName: "NAME OF BOT"
queryUUID: "UUID OF YOUR QUERY"
supporterGroupId: "GROUP ID OF YOUR SUPPORT SERVER GROUP"
busyGroupId: "GROUP ID OF YOUR BUSY SERVER GROUP"
supportMessage: "MESSAGE THAT GET THE SUPPORTER"
defaultChannelId: "ID OF YOUR ENTRANCEHALL"
supportChannelId: "ID OF YOUR SUPPORT CHANNEL"
listRefreshTime: "TIME IN WHICH YOUR USERLIST GET REFRESHED (recommend is 2000)"
