host: "authum.de"
queryPort: 10011
queryName: "querry"
queryPassword: "PfQyMopI"
virtualServerId: 1
queryUserName: "Support"
queryUUID: "lAGjYOK+SAqKBDj1UkXr2yK/tqM="
defaultChannelId: 1
supportChannelId: 2
listRefreshTime: 2000

